// Enums and Types - Must match backend enum values exactly
export enum MaintenanceType {
  PREVENTIVE = 'Preventive',
  CORRECTIVE = 'Corrective',
  PREDICTIVE = 'Predictive',
  EMERGENCY = 'Emergency'
}

export enum MaintenanceStatus {
  SCHEDULED = 'Scheduled',
  IN_PROGRESS = 'InProgress',
  COMPLETED = 'Completed',
  CANCELLED = 'Cancelled',
  OVERDUE = 'Overdue'
}

export enum AlertType {
  SERVICE_DUE = 'SERVICE_DUE',
  OVERDUE = 'OVERDUE'
}

export enum Priority {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW'
}

// Core Interfaces
export interface MaintenanceJob {
  id: number;
  machineId: number;
  machineName: string;
  machineModel: string;
  serialNumber?: string;
  projectId?: number;
  projectName?: string;
  project?: string; // Kept for backward compatibility with components
  maintenanceReportId?: number;
  reportTicketId?: string;
  scheduledDate: Date;
  completedDate?: Date;
  type: MaintenanceType;
  status: MaintenanceStatus;
  assignedTo?: string[];
  assignments?: MaintenanceJobAssignment[];
  estimatedHours: number;
  actualHours?: number;
  reason: string;
  observations?: string;
  partsReplaced?: string[];

  // From linked report for context
  symptoms?: string[];
  errorCodes?: string;
  severity?: string;

  // New: Consumed Drilling Components (added at job completion)
  isServiceCompleted?: boolean;
  isEngineServiceCompleted?: boolean;
  isDrifterServiceCompleted?: boolean;
  drillBitsUsed?: number;
  drillBitType?: string;
  drillRodsUsed?: number;
  drillRodType?: string;
  shanksUsed?: number;
  shankType?: string;

  // Auto-generated service alert fields
  isAutoGenerated?: boolean;
  serviceAlertLevel?: string; // "Medium", "High", "Critical"

  attachments?: FileAttachment[];
  createdAt?: Date;
  updatedAt?: Date;
}

export interface MaintenanceJobAssignment {
  id: number;
  maintenanceJobId: number;
  mechanicalEngineerId: number;
  mechanicalEngineerName?: string;
  assignedAt: Date;
}

export interface MaintenanceAlert {
  id: number;
  machineId: number;
  machineName: string;
  alertType: AlertType;
  message: string;
  dueDate: Date;
  priority: Priority;
  daysPastDue?: number;
  daysUntilDue?: number;
}

export interface MaintenanceStats {
  totalMachines: number;
  scheduledJobs: number;
  inProgressJobs: number;
  completedJobs: number;
  overdueJobs: number;
  serviceDueAlerts: number;
}

export interface MachineMaintenanceHistory {
  machineId: number;
  machineName: string;
  model: string;
  serialNumber: string;
  currentStatus: string;
  lastServiceDate: Date;
  nextServiceDate: Date;
  engineHours: number;
  serviceHours: number;
  idleHours: number;
  maintenanceRecords: MaintenanceRecord[];
}

export interface MaintenanceRecord {
  id: number;
  date: Date;
  type: MaintenanceType;
  description: string;
  technician: string;
  hoursSpent: number;
  partsUsed?: string[];
  notes?: string;
}

export interface FileAttachment {
  id: number;
  fileName: string;
  fileType: string;
  fileSize: number;
  uploadedAt: Date;
  url: string;
}

export interface ServiceIntervalConfig {
  machineType: string;
  intervalHours?: number;
  intervalMonths?: number;
  alertWindowDays: number;
}

export interface JobFilters {
  dateRange?: { start: Date; end: Date };
  status?: MaintenanceStatus[];
  machineType?: string[];
  project?: string[];
  assignedTo?: string[];
  searchTerm?: string;
}

export interface NotificationPreferences {
  emailNotifications: boolean;
  inAppNotifications: boolean;
  alertWindowDays: number;
  overdueNotifications: boolean;
  
  // Advanced notification settings
  emailFrequency?: 'immediate' | 'daily' | 'weekly';
  quietHoursEnabled?: boolean;
  quietHoursStart?: string;
  quietHoursEnd?: string;
  weekendNotifications?: boolean;

  // Notification type preferences
  serviceDueEmail?: boolean;
  serviceDueInApp?: boolean;
  overdueEmail?: boolean;
  overdueInApp?: boolean;
  jobAssignedEmail?: boolean;
  jobAssignedInApp?: boolean;
  jobCompletedEmail?: boolean;
  jobCompletedInApp?: boolean;
  systemAlertsEmail?: boolean;
  systemAlertsInApp?: boolean;

  // Escalation settings
  escalationEnabled?: boolean;
  escalationDelayHours?: number;
  escalationRecipients?: string[];
}

// Analytics Interfaces
export interface ServiceComplianceData {
  onTime: number;
  overdue: number;
  percentage: number;
}

export interface MTBFMetrics {
  machineType: string;
  mtbfHours: number;
  periodMonths: number;
  failureCount: number;
}

export interface PartsUsageData {
  partName: string;
  usageCount: number;
  totalCost: number;
  machineTypes: string[];
}

export interface UsageMetrics {
  machineId: number;
  engineHours: number;
  idleHours: number;
  serviceHours: number;
  lastUpdated: Date;
}

// ===================================================================
// JOB COMPLETION REQUEST - Matches Backend
// ===================================================================
export interface CompleteMaintenanceJobRequest {
  observations: string;
  actualHours: number;
  partsReplaced?: string[];

  // Service completion flags - reset respective service hours when true
  isServiceCompleted: boolean;
  isEngineServiceCompleted: boolean;
  isDrifterServiceCompleted: boolean;

  // Consumed drilling components
  drillBitsUsed?: number;
  drillBitType?: string;
  drillRodsUsed?: number;
  drillRodType?: string;
  shanksUsed?: number;
  shankType?: string;
}