using System;
using System.Collections.Generic;

namespace API.Models;

public partial class MaintenanceJob
{
    public int Id { get; set; }

    public int MachineId { get; set; }

    public int? ProjectId { get; set; }

    public int? MaintenanceReportId { get; set; }

    public string Type { get; set; } = null!;

    public string Status { get; set; } = null!;

    public DateTime ScheduledDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public DateTime? InProgressAt { get; set; }

    public decimal EstimatedHours { get; set; }

    public decimal? ActualHours { get; set; }

    public string Reason { get; set; } = null!;

    public string? Observations { get; set; }

    public string? PartsReplaced { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public string? DrillBitType { get; set; }

    public int? DrillBitsUsed { get; set; }

    public string? DrillRodType { get; set; }

    public int? DrillRodsUsed { get; set; }

    public bool IsServiceCompleted { get; set; }

    public string? ShankType { get; set; }

    public int? ShanksUsed { get; set; }

    public bool IsAutoGenerated { get; set; }

    public bool IsDrifterServiceCompleted { get; set; }

    public bool IsEngineServiceCompleted { get; set; }

    public string? ServiceAlertLevel { get; set; }

    public virtual User CreatedByNavigation { get; set; } = null!;

    public virtual Machine Machine { get; set; } = null!;

    public virtual ICollection<MaintenanceJobAssignment> MaintenanceJobAssignments { get; set; } = new List<MaintenanceJobAssignment>();

    public virtual MaintenanceReport? MaintenanceReport { get; set; }

    public virtual Project? Project { get; set; }
}
