import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../environments/environment';

export interface MaintenanceJobAssignment {
  id: number;
  maintenanceJobId: number;
  mechanicalEngineerId: number;
  mechanicalEngineerName: string;
  assignedAt: string;
}

export interface MaintenanceJobDto {
  id: number;
  machineId: number;
  machineName: string;
  machineModel: string;
  serialNumber: string;
  projectId: number | null;
  projectName: string | null;
  maintenanceReportId: number | null;
  reportTicketId: string | null;
  type: string;
  status: string;
  scheduledDate: string;
  completedDate: string | null;
  estimatedHours: number;
  actualHours: number | null;
  reason: string;
  observations: string | null;
  partsReplaced: string[] | null;
  assignments: MaintenanceJobAssignment[];
  symptoms: string[] | null;
  errorCodes: string | null;
  severity: string | null;
  isServiceCompleted: boolean;
  isAutoGenerated: boolean;
  serviceAlertLevel: string | null;
  drillBitsUsed: number | null;
  drillBitType: string | null;
  drillRodsUsed: number | null;
  drillRodType: string | null;
  shanksUsed: number | null;
  shankType: string | null;
}

export interface MaintenanceStatsDto {
  totalJobs: number;
  scheduledJobs: number;
  inProgressJobs: number;
  completedJobs: number;
  overdueJobs: number;
  emergencyJobs: number;
  averageCompletionHours: number;
  serviceDueCount: number;
}

export interface ServiceDueAlertDto {
  machineId: number;
  machineName: string;
  serialNumber: string;
  projectName: string;
  serviceType: string;
  currentHours: number;
  intervalHours: number;
  percentageUsed: number;
  hoursRemaining: number;
  alertLevel: string;
}

@Injectable({
  providedIn: 'root'
})
export class MaintenanceJobService {
  private apiUrl = `${environment.apiUrl}/api/maintenance-jobs`;
  private machinesApiUrl = `${environment.apiUrl}/api/machines`;

  constructor(private http: HttpClient) {}

  getAllJobs(filters?: {
    status?: string;
    type?: string;
    machineId?: number;
    startDate?: Date;
    endDate?: Date;
  }): Observable<MaintenanceJobDto[]> {
    let params = new HttpParams();

    if (filters?.status) {
      params = params.set('status', filters.status);
    }
    if (filters?.type) {
      params = params.set('type', filters.type);
    }
    if (filters?.machineId) {
      params = params.set('machineId', filters.machineId.toString());
    }
    if (filters?.startDate) {
      params = params.set('startDate', filters.startDate.toISOString());
    }
    if (filters?.endDate) {
      params = params.set('endDate', filters.endDate.toISOString());
    }

    return this.http.get<MaintenanceJobDto[]>(`${this.apiUrl}/all`, { params });
  }

  getJobById(id: number): Observable<MaintenanceJobDto> {
    return this.http.get<MaintenanceJobDto>(`${this.apiUrl}/${id}`);
  }

  getMaintenanceStats(regionId?: number): Observable<MaintenanceStatsDto> {
    const url = regionId
      ? `${this.apiUrl}/stats/region/${regionId}`
      : `${this.apiUrl}/stats/region/0`;
    return this.http.get<MaintenanceStatsDto>(url);
  }

  getServiceAlerts(): Observable<ServiceDueAlertDto[]> {
    return this.http.get<ServiceDueAlertDto[]>(`${this.machinesApiUrl}/service-alerts`);
  }

  getOverdueJobs(): Observable<MaintenanceJobDto[]> {
    return this.http.get<MaintenanceJobDto[]>(`${this.apiUrl}/overdue`);
  }
}
