using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddServiceAlertFieldsToMaintenanceJob : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "MaintenanceJobs",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDrifterServiceCompleted",
                table: "MaintenanceJobs",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsEngineServiceCompleted",
                table: "MaintenanceJobs",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "ServiceAlertLevel",
                table: "MaintenanceJobs",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6175), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6176) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6181), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6182) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6185), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6185) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6187), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6187) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6189), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6190) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6191), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6192) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6194), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6194) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 8,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6196), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6205) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6383), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6383) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6392), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6393) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6396), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6396) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6398), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6399) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6401), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6401) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6403), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6404) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6406), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6407) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 8,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6409), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6409) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 9,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6411), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6411) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 10,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6413), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6414) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 11,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6416), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6416) });

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 1,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6259));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 2,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6263));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 3,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6264));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 4,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6266));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 5,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6267));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 6,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6269));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 7,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6270));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 8,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6271));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 9,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(6273));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5942), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5945) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5957), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5957) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5960), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5960) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5962), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5962) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5965), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5965) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5967), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5967) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5969), new DateTime(2025, 11, 21, 7, 55, 27, 764, DateTimeKind.Utc).AddTicks(5969) });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "MaintenanceJobs");

            migrationBuilder.DropColumn(
                name: "IsDrifterServiceCompleted",
                table: "MaintenanceJobs");

            migrationBuilder.DropColumn(
                name: "IsEngineServiceCompleted",
                table: "MaintenanceJobs");

            migrationBuilder.DropColumn(
                name: "ServiceAlertLevel",
                table: "MaintenanceJobs");

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9630), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9630) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9636), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9636) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9640), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9640) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9643), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9643) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9646), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9647) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9649), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9650) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9652), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9653) });

            migrationBuilder.UpdateData(
                table: "Permissions",
                keyColumn: "Id",
                keyValue: 8,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9655), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9656) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(104), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(105) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(125), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(125) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(129), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(129) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(132), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(133) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(136), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(136) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(139), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(140) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(143), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(143) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 8,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(146), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(147) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 9,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(149), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(150) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 10,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(153), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(153) });

            migrationBuilder.UpdateData(
                table: "Regions",
                keyColumn: "Id",
                keyValue: 11,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(156), new DateTime(2025, 11, 20, 3, 56, 55, 552, DateTimeKind.Utc).AddTicks(157) });

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 1,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9776));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 2,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9779));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 3,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9781));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 4,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9782));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 5,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9784));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 6,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9785));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 7,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9787));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 8,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9789));

            migrationBuilder.UpdateData(
                table: "RolePermissions",
                keyColumn: "Id",
                keyValue: 9,
                column: "GrantedAt",
                value: new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9914));

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9102), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9107) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9171), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9172) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9175), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9176) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9178), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9179) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9181), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9182) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9184), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9185) });

            migrationBuilder.UpdateData(
                table: "Roles",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "CreatedAt", "UpdatedAt" },
                values: new object[] { new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9187), new DateTime(2025, 11, 20, 3, 56, 55, 551, DateTimeKind.Utc).AddTicks(9188) });
        }
    }
}
